// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using egibi_api.Data;

#nullable disable

namespace egibi_api.Migrations
{
    [DbContext(typeof(EgibiDbContext))]
    [Migration("20250107174655_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("egibi_api.Data.Entities.Connection", b =>
                {
                    b.Property<int>("ConnectionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConnectionID"));

                    b.Property<int?>("ConnectionTypeID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ConnectionID");

                    b.HasIndex("ConnectionTypeID");

                    b.ToTable("Connection");

                    b.HasData(
                        new
                        {
                            ConnectionID = 1,
                            ConnectionTypeID = 1,
                            Name = "Binance US"
                        });
                });

            modelBuilder.Entity("egibi_api.Data.Entities.ConnectionType", b =>
                {
                    b.Property<int>("ConnectionTypeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ConnectionTypeID"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("ConnectionTypeID");

                    b.ToTable("ConnectionType");

                    b.HasData(
                        new
                        {
                            ConnectionTypeID = 1,
                            Description = "Connection properties for a 3rd party API",
                            Name = "api"
                        });
                });

            modelBuilder.Entity("egibi_api.Data.Entities.Connection", b =>
                {
                    b.HasOne("egibi_api.Data.Entities.ConnectionType", "ConnectionType")
                        .WithMany("Connections")
                        .HasForeignKey("ConnectionTypeID");

                    b.Navigation("ConnectionType");
                });

            modelBuilder.Entity("egibi_api.Data.Entities.ConnectionType", b =>
                {
                    b.Navigation("Connections");
                });
#pragma warning restore 612, 618
        }
    }
}
